#include <iostream>

using namespace std;

const char FULL_BLOCK = 219;
const char LOWER_HAFT_BLOCK = 220;
const char UPPER_HAFT_BLOCK = 223;
const char LIGHT_SHADE = 178; //Correct Code: 176
const char MEDIUM_SHADE = 178; //Correct Code: 177
const char DARK_SHADE = 178;
const char SP = 32; //Whitespace

//Width  : 45 characters
//Height : 6 lines
int main()
{
	// Line 1
	cout << SP << SP << SP << SP << SP << LOWER_HAFT_BLOCK << SP << SP << SP << SP << SP << SP << SP << SP
		<< SP << SP << SP << SP << SP << LOWER_HAFT_BLOCK << FULL_BLOCK << LOWER_HAFT_BLOCK 
		<< SP << FULL_BLOCK << LOWER_HAFT_BLOCK << SP << SP << SP << SP << SP << SP << LOWER_HAFT_BLOCK << endl;
	
	//cout << "\n";

	// Line 2
	cout << SP << LOWER_HAFT_BLOCK << FULL_BLOCK << UPPER_HAFT_BLOCK << FULL_BLOCK << DARK_SHADE << SP << LOWER_HAFT_BLOCK 
		<< DARK_SHADE << UPPER_HAFT_BLOCK << UPPER_HAFT_BLOCK << FULL_BLOCK << UPPER_HAFT_BLOCK << SP << UPPER_HAFT_BLOCK
		<< UPPER_HAFT_BLOCK << UPPER_HAFT_BLOCK << FULL_BLOCK << DARK_SHADE << UPPER_HAFT_BLOCK << UPPER_HAFT_BLOCK << SP << UPPER_HAFT_BLOCK 
		<< UPPER_HAFT_BLOCK << SP << SP << SP << LOWER_HAFT_BLOCK << FULL_BLOCK << UPPER_HAFT_BLOCK << FULL_BLOCK << DARK_SHADE
		<< UPPER_HAFT_BLOCK << UPPER_HAFT_BLOCK << UPPER_HAFT_BLOCK << UPPER_HAFT_BLOCK << UPPER_HAFT_BLOCK << DARK_SHADE 
		<< LOWER_HAFT_BLOCK << UPPER_HAFT_BLOCK << FULL_BLOCK << FULL_BLOCK << UPPER_HAFT_BLOCK << UPPER_HAFT_BLOCK << endl;

	//cout << "\n";

	// Line 3
	cout << FULL_BLOCK << FULL_BLOCK << SP << SP << FULL_BLOCK << FULL_BLOCK << SP << UPPER_HAFT_BLOCK
		<< FULL_BLOCK << FULL_BLOCK << LOWER_HAFT_BLOCK << LOWER_HAFT_BLOCK << SP << LOWER_HAFT_BLOCK 
		<< FULL_BLOCK << SP << SP << UPPER_HAFT_BLOCK << SP << LIGHT_SHADE << MEDIUM_SHADE << SP << LIGHT_SHADE 
		<< MEDIUM_SHADE << SP << SP << SP << FULL_BLOCK << FULL_BLOCK << SP << SP << FULL_BLOCK << FULL_BLOCK << SP
		<< LOWER_HAFT_BLOCK << FULL_BLOCK << LOWER_HAFT_BLOCK << SP << FULL_BLOCK << UPPER_HAFT_BLOCK << SP << FULL_BLOCK << FULL_BLOCK << endl;

	//cout << "\n";

	// Line 4
	cout << FULL_BLOCK << DARK_SHADE << LOWER_HAFT_BLOCK << UPPER_HAFT_BLOCK << FULL_BLOCK << FULL_BLOCK << SP << SP
		<< LOWER_HAFT_BLOCK << SP << UPPER_HAFT_BLOCK << FULL_BLOCK << FULL_BLOCK << SP << DARK_SHADE << FULL_BLOCK 
		<< SP << SP << SP << MEDIUM_SHADE << DARK_SHADE << SP << MEDIUM_SHADE << DARK_SHADE << SP << SP << SP << FULL_BLOCK
		<< DARK_SHADE << LOWER_HAFT_BLOCK << UPPER_HAFT_BLOCK << FULL_BLOCK << FULL_BLOCK << SP << DARK_SHADE << FULL_BLOCK
		<< SP << UPPER_HAFT_BLOCK << LOWER_HAFT_BLOCK << SP << SP << FULL_BLOCK << DARK_SHADE << endl;
	
	//cout << "\n";

	// Line 5
	cout << FULL_BLOCK << MEDIUM_SHADE << SP << SP << FULL_BLOCK << DARK_SHADE << SP << FULL_BLOCK << FULL_BLOCK 
		<< LOWER_HAFT_BLOCK << DARK_SHADE << UPPER_HAFT_BLOCK << SP << UPPER_HAFT_BLOCK << FULL_BLOCK << LOWER_HAFT_BLOCK 
		<< LOWER_HAFT_BLOCK << FULL_BLOCK << LOWER_HAFT_BLOCK << DARK_SHADE << FULL_BLOCK << SP << DARK_SHADE << FULL_BLOCK 
		<< SP << SP << SP << FULL_BLOCK << MEDIUM_SHADE << SP << SP << FULL_BLOCK << DARK_SHADE << SP << MEDIUM_SHADE 
		<< FULL_BLOCK << SP << SP << DARK_SHADE << FULL_BLOCK << LOWER_HAFT_BLOCK << SP << MEDIUM_SHADE << endl;

	//cout << "\n";

	// Line 6
	cout << SP << SP << SP << SP << UPPER_HAFT_BLOCK << MEDIUM_SHADE << SP << SP << SP 
		<< SP << SP << SP << SP << SP << SP << SP << SP << UPPER_HAFT_BLOCK << SP << SP
		<< UPPER_HAFT_BLOCK << SP << FULL_BLOCK << UPPER_HAFT_BLOCK << SP << SP << SP
		<< SP << SP << SP << SP << UPPER_HAFT_BLOCK 
		<< MEDIUM_SHADE << SP << SP << UPPER_HAFT_BLOCK << SP << SP << FULL_BLOCK 
		<< UPPER_HAFT_BLOCK << SP << SP << LIGHT_SHADE<<endl;

	return 0;
}